###
GET http://127.0.0.1:8021/u/v1/user/list HTTP/1.1
x-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJRCI6MTMsIk5pY2tOYW1lIjoibW9iYjIiLCJBdXRob3JpdHlJZCI6MiwiZXhwIjoxNzEwNjA0MDYzLCJpc3MiOiJMTVhMSkxYIiwibmJmIjoxNzA4MDEyMDYzfQ.R2crLjqN0DfMnLukj2ALkG9-RHLEhFn_euukonEw6cU

###
POST http://127.0.0.1:8021/u/v1/base/send_sms HTTP/1.1
Content-Type: application/json

{
  "mobile": "17322611869",
  "type": 1
}

###
POST http://localhost:8021/u/v1/user/pwd_login HTTP/1.1
Content-Type: application/json

{
  "mobile": "18782222220",
  "password": "admin123"
}

###
GET http://localhost:8021/u/v1/base/captcha HTTP/1.1